### PR TITLE
Python3 + PEP8 + Cleanup and some organization

### PR DESCRIPTION
**Pull request by TomFaulkner**
I built upon @SillySam's Python 3 fork and made things more pythonic and compliant with the PEP8 style guide. It's not quite all transitioned yet, but it should serve as a good start.

### CODE REVIEW

**Comment by Griffintaur** [comment]
@TomFaulkner i have created another branch for python 3 .Please let me know if conflicts can be fixed.

**Comment by TomFaulkner** [comment]
It still needs work as I mentioned, but no conflicts now. I changed too much of the file too quickly for git to see the rename. :)

**Comment by TomFaulkner** [comment]
This should close #18 as well.

Closes #18.

**Comment by TomFaulkner** [comment]
Sorry about that, deleted the branch prematurely.

**Pull request merged**
